spring.application.name=signing-simulator


spring.datasource.url=jdbc:postgresql://localhost:5431/signingSimulatorDB
spring.datasource.username = postgres
spring.datasource.password = admin
spring.datasource.driver-class-name = org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create-drop

spring.devtools.restart.enabled=false


allow.notLoggedUsers=true