spring.application.name=signing-simulator

spring.profiles.active=${ACTIVE_PROFILE:local}

spring.datasource.url=${DB_POSTGRES_URL}
spring.datasource.username = ${DB_POSTGRES_USER}
spring.datasource.password = ${DB_POSTGRES_PASSWORD}

spring.datasource.driver-class-name = org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create-drop

spring.devtools.restart.enabled=false

allow.notLoggedUsers=true


# Kafka
kafka-config.bootstrap-servers=${KAFKA_CONFIG_BOOTSTRAP_SERVERS}

kafka-producer-config.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka-producer-config.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


kafka-consumer-config.group-id=signing-simulator-group-1
kafka-consumer-config.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka-consumer-config.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
kafka-consumer-config.trusted-packages=*