services:


  db-postgresql:
    image: postgres:17.5-alpine
    container_name: signing-simulator-db-postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: signingSimulatorDB
    ports:
      - "5431:5432"
    volumes:
      - db-postgresql-vol:/var/lib/postgresql/data

volumes:
  db-postgresql-vol:
